apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coco-tenant

resources:
- ../overlays

images:
- name: kbs-container-image
  newName: quay.io/fidencio/trustee
  newTag: idc-sdp-cloud-v0.0.3

patches:
- path: add_ita_token_certs.yaml
  target:
    kind: Deployment
    name: kbs

configMapGenerator:
- name: kbs-config
  behavior: replace
  files:
  - kbs-config.toml
- name: ita-token-cert
  files:
  - intel-trust-authority-certs.txt
